### PR TITLE
Bump client-go to 2.0.0 for k8s 1.5 support

### PR DESCRIPTION
**Pull request by a-palchikov**
Overall it feels that we should not commit the vendor directory and instead rely on glide to fetch the required version.

### CODE REVIEW

**Comment by klizhentas** [comment]
@a-palchikov let's move off glide - it does not support updating individual dependencies, we can try using go standard dep tool 

https://github.com/golang/dep

**Comment by a-palchikov** [comment]
Glide is not supporting individual package updates on purpose

**Comment by a-palchikov** [comment]
Do you want to migrate to dep in this PR?

**Comment by klizhentas** [comment]
no, not really, just a general note

**Pull request merged**
