### PR TITLE
Migrate to gomod

### PR DESCRIPTION
**Pull request by eldios**
Migrate to gomod

### CODE REVIEW

**Review by wadells — COMMENTED** [review]
Testing done

I don't see any changes to the Makefile. In particular, the mismatch between `go 1.15` in the go mod and `go1.12.9-buster` in the Makefile seems relevant.  This spans go 1.14 where the default behavior of `--mod=vendor` changed.

**Comment by eldios** [comment]
> Testing done?
> 
> I don't see any changes to the Makefile. In particular, the mismatch between `go 1.15` in the go mod and `go1.12.9-buster` in the Makefile seems relevant. This spans go 1.14 where the default behavior of `--mod=vendor` changed.

This might be related to the Go version I have installed.

I built the rig binary and it's working with my manual tests.

Not sure if the go version in the go.mod file can create issues or not :shrug: but I agree that the two should definitely match.

**Review by wadells — APPROVED** [review]

**Comment by wadells** [comment]
> I built the rig binary and it's working with my manual tests.

Did you do this with the containerized Makefile build or your local go?   I wouldn't expect there to be signifigant differences, but better safe than sorry.

**Comment by eldios** [comment]
both locally and with docker and no changes

**Pull request merged**
